# RUN IN LINUX W/ singularity
# Python 27, 34-37
# RUN IN MACOS on all possible python versions
# Paralellise
# Factor out

env:
  - TRAVIS_PYTHON_VERSION=py27 PYENV_VERSION=2.7.14
  - TRAVIS_PYTHON_VERSION=py34 PYENV_VERSION=3.4.7
  - TRAVIS_PYTHON_VERSION=py35 PYENV_VERSION=3.5.4
  - TRAVIS_PYTHON_VERSION=py36 PYENV_VERSION=3.6.3
  - TRAVIS_PYTHON_VERSION=py37 PYENV_VERSION=3.7-dev

matrix:
  include:
    - os: linux
      language: python
    - os: osx
      language: generic

install:
  - bash $TRAVIS_BUILD_DIR/travis/os_install.sh
  - pip install tox-travis

script:
  - tox

cache:
  pip: true
  directories:
    - .mypy_cache



branches:
  only:
    - master
notifications:
  email: false

#dist: trusty
#sudo: required
#services:
#  - docker
#
#before_install:
#- wget -O- http://neuro.debian.net/lists/trusty.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
#- sudo apt-key add .travis.singularity_key.txt
#- sudo apt-get update
#- sudo apt-get install -y singularity-container
#
#language: python
#cache:
#  pip: true
#  directories:
#    - .mypy_cache
#
#os:
#  - linux
#install:
#  - pip install tox-travis
#jobs:
#  include:
#    - stage: test
#      python: "2.7"
#    - stage: test
#      python: "3.4"
#    - stage: test
#      python: "3.5"
#    - stage: test
#      python: "3.6"
#    - stage: test
#      python: "3.7"
#      dist: xenial
#    - stage: release-test
#      python: "2.7"
#      script: RELEASE_SKIP=head ${TRAVIS_BUILD_DIR}/release-test.sh
#script: tox
#branches:
#  only:
#    - master
#notifications:
#  email: false
