
matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      env: TRAVIS_PYTHON_VERSION=py27
    - os: linux
      language: python
      python: 3.4
      env: TRAVIS_PYTHON_VERSION=py34
    - os: linux
      language: python
      python: 3.5
      env: TRAVIS_PYTHON_VERSION=py35
    - os: linux
      language: python
      python: 3.6
      env: TRAVIS_PYTHON_VERSION=py36
    - os: linux
      language: python
      python: 3.7-dev
      env: TRAVIS_PYTHON_VERSION=py37
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=py27 PYENV_VERSION=2.7.14
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=py34 PYENV_VERSION=3.4.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=py35 PYENV_VERSION=3.5.4
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=py36 PYENV_VERSION=3.6.3
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=py37 PYENV_VERSION=3.7-dev

    - stage: release-test
      os: linux
      python: 2.7
      script: RELEASE_SKIP=head ${TRAVIS_BUILD_DIR}/release-test.sh
install:
  - bash $TRAVIS_BUILD_DIR/travis/os_install.sh
  - pip install tox-travis

script:
  - tox

cache:
  pip: true
  directories:
    - .mypy_cache

branches:
  only:
    - master
notifications:
  email: false
