services:
  - docker

matrix:
  include:
    - os: linux WORKING
      language: python
      python: 2.7
    - os: linux WORKING
      language: python
      python: 3.4
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      dist: xenial
      language: python
      python: 3.7 # Sudo is required with xenial and python 3.7, see
      sudo: true # https://github.com/travis-ci/travis-ci/issues/9831#issuecomment-401757065

    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7 PYENV_VERSION=2.7.15
    - os: osx WORKING
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.4 PYENV_VERSION=3.4.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5 PYENV_VERSION=3.5.4
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6 PYENV_VERSION=3.6.3
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 PYENV_VERSION=3.7-dev

    - os: linux WORKING
      language: python
      python: 2.7
      name: RELEASE
      script: RELEASE_SKIP=head ${TRAVIS_BUILD_DIR}/release-test.sh
install:
  - source $TRAVIS_BUILD_DIR/travis/os_install.sh
  - python --version
  - pip install tox-travis

script:
  - tox

before_cache:
  - brew cleanup
cache:
  pip: true
  directories:
    - .mypy_cache
    - $HOME/.pyenv_cache
    - $HOME/Library/Caches/Homebrew
    - $HOME/.pyenv/versions

branches:
  only:
    - master
notifications:
  email: false
